# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
# Enable Gradle build cache
org.gradle.caching=true
# Enable Gradle configuration cache
org.gradle.configuration-cache=true

# Metadata
group=dev.upcraft.bifrost
mod_id=bifrost
mod_description=A mod about dreamlike dimensions with rainbow bridges.
mod_display_name=Bifrost Dimension
sources_url=https://github.com/Up-Mods/Bifrost
issues_url=https://github.com/Up-Mods/Bifrost/issues
license_url=https://github.com/Up-Mods/Bifrost/blob/HEAD/LICENSE.md
discord_url=https://mods.upcraft.dev/discord
#homepage_url=https://github.com/Up-Mods/Bifrost
#curseforge_id=0
#modrinth_id=0
